name: ci

on:
  pull_request:

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build
        run: docker build -t helix-p4d .
